language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: VERBOSE=true ./vendor/bin/tester -c ./tests/php.ini -j 40 ./tests
