version: 2

jobs:
  build:
    docker:
      - image: docker:20

    steps:
      - checkout

      - run: apk add make
      - run: make build
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: make install

      - run: make test
